### ISSUE TITLE
Is Pure dead?

### ISSUE THREAD

**Issue by grantmcconnaughey** [pure-css/pure#289]
No point update in the last 5 months. I've seen a few commits here and there, but the updates have really slowed lately. Is development on Pure still active?

**Comment by deathmood** [comment]
I would like to ask this question too(( Of course I've read pure roadmap that says smth about 0.7.0 release in Q3 this year, but there are no new commits since April and so many opened issues...

I do really like Pure, but I need to know, should I consider it for my next projects or no((
So is Pure dead?

**Comment by lkraav** [comment]
I'm using Pure exclusively since 0.2.0 to today, and nothing has been broken across double-digit site count, a ton of devices tested etc. But it'd be interesting to see some kind of a roadmap of what should be targeted for a new release (there may still be functional problems I don't know about), and perhaps a community effort could be built (I'd be willing to put in recurring money) to push fresh releases.

**Comment by deathmood** [comment]
https://github.com/yahoo/pure/issues/414 - here is roadmap - but according to this they should release pure 0.7.0 in Q2 2015 and 1.0 in Q3. Now it is the end of Q3 and no new releases(((

**Comment by yyil** [comment]
May 2016.. Still nuttin'

**Comment by tivac** [comment]
#557, @lkraav is taking over once Y! hands over the keys.

**Comment by cooperdozier** [comment]
very glad to hear it. i use exclusively html css and pure pretty much for
the last

**Comment by cooperdozier** [comment]
for the last 4 years. i was unaware its future was in question. it will be
interesting to see where pure goes when it is an independent rather than a
yahoo project. i tried bootstrap a little. too complicated and heavy.
documentation on some things was either broken or i just couldnt figure it
out.

**Comment by erkidhoxholli** [comment]
Sorry to disturb you guys but I was wondering will you keep updating pure ? I like its minimalistic feel and size. Cheers !

**Comment by redonkulus** [comment]
Thanks for the questions/concerns. We just haven't had time to sync on the process. We have some important releases that are taking our time right now. Hopefully we can sync up soon (a couple of weeks). Of course I said this before too, so we will see.

I'm going to lock this convo since we already have https://github.com/yahoo/pure/issues/557. Thanks!
