### ISSUE TITLE
`type="date"` input sizing issues

### ISSUE THREAD

**Issue by danielsokolowski** [pure-css/pure#395]
![image](https://cloud.githubusercontent.com/assets/273413/4837494/64481d46-5fd7-11e4-8fb2-28a2d4cf1e93.png)

**Comment by jamesalley** [comment]
Nice one. I'm going to leave this issue open for awhile, because it is something we need to revisit from time to time.

Firefox and Safari (desktop) don't yet support this input type. Only Chrome and iOS/Android do. 

I've looked into the issue to see if I could fix it by adjusting padding. I can fix it for Chrome, but that will break other browsers, which currently will ignore the type="date" and render the element as a regular text field, properly sized. 

I noticed other problems with this input type as well. Chrome doesn't color the input's text properly. Also, iOS has a completely different implementation than Chrome; annoyingly, the element renders too high in the [test file] (http://jsfiddle.net/james_alley/s5pfsbLq/) I wrote, and then renders too low after the control is used.

Then there are other types we will need to consider, like datetime, which will also likely be problematic.

It may simply be too early; we may need to wait for implementations to arrive and settle down before we can address this.
