### ISSUE TITLE
pure horizontal menu is not responsive

### ISSUE THREAD

**Issue by pioc92** [pure-css/pure#440]
Hi, i'm trying the 0.6.0-rc-1 release and the pure-menu horizontal isn't responsive as the 0.5.0 was.
Is-it possible to conserve this in this release?
Sorry for my english and if the response is somewhere here ;-)
![puremenu-0 5](https://cloud.githubusercontent.com/assets/592857/6232932/b93a9564-b6cf-11e4-877a-09413bb01dd2.png)
![puremenu-0 6 0rc1](https://cloud.githubusercontent.com/assets/592857/6232933/b944bc06-b6cf-11e4-882f-ee2dc6e11775.png)

**Comment by jamesalley** [comment]
Menu in 0.6.0 is definitely different from the previous Menu construct, and not entirely backwards compatible-- especially if you are using YUI's Y.Menu. For many users, though, adapting to the new menu should be possible. For instance, I didn't have much trouble updating all the menus on the Pure-site, including all the example layouts. I mainly just had to add classnames for `.pure-menu-item` and `.pure-menu-link`.

That said, let's look at little more closely at the problem you're having. While your description is a little thin, from the image you provide, it seems as though you're pointing out that a horizontal menu no longer wraps to a new line if there is not enough room for it. That is not an oversight; it was intentional. It's also worthy of discussion; it's exactly this sort of change about which I was hoping to get feedback. So thank you for posing this question. I'll try to rephrase the question succinctly:

## Should `.pure-menu-horizontal` wrap?

I don't believe it should, because:

* If it wraps, it starts to take on the characteristics of a vertical menu, and if you wanted a vertical menu, you wouldn't be using `.pure-menu-horizontal`.
* If the menu doesn't wrap, that can be a good cue to a desktop/big viewport user that they should make their window a little wider. It's common with desktop UI to have a min-width spec for the site; not every layout is entirely responsive down.
* As the [example layouts](http://stage.purecss.io/layouts/) show, there are various ways to make a very wide horizontal menu respond to narrow window widths:
    * You could use the `.pure-menu-scrollable` class.
    * You could convert it to a [tucked-away vertical menu](http://stage.purecss.io/layouts/tucked-menu-vertical/).
    * You could make it non-scrollable at wide widths, but [tucked away (and scrollable)](http://stage.purecss.io/layouts/tucked-menu/) at narrow widths.
* Anecdotally, if I make `.pure-menu-horizontal` wrap by default, most (if not all) of the implementations on the Pure-site and in the test files within the Pure repo look bad.

All of this leads me to think that `.pure-menu-horizontal` should not wrap by default. My hope is that Pure menu provides a solid foundation for simple menus, that creative developers can easily build upon to create more complex, custom solutions.

## But what if I really want my horizontal menu to wrap?

Create a custom class and apply it to your menu:
```
.custom-may-wrap {
    white-space: normal;
}
```
Or override: 
```
.pure-menu-horizontal {
    white-space: normal;
}
```

**Comment by pioc92** [comment]
Thank you for your answer. I use a css framework to help me to do responsive websites easily and quickly. So that's why i asked you that question as the menu don't resize even with the grids-responsive.css. Thank you so much, now i understand. But i think that for newbee like me, we dont Know why this menu stay on mobile like on desktop.

**Comment by jamesalley** [comment]
I think it's worthy of discussion. Perhaps we should add a helper class to the library and then mention it in the documentation, with a warning to developers to be careful about using horizontal menus, as you're making an assumption about the window width when you use them, unless you use the `.pure-menu-scrollable` classname.

```
.pure-menu-may-wrap {
    white-space: normal;
}
```

Do you think something like that would be helpful and provide clarity on this issue?

**Comment by pioc92** [comment]
Before i ask you on github i spend one hour on the menu... ;-) i think other people using pure menus will find this very helpful

**Comment by jamesalley** [comment]
OK. Sounds like I should add a note to the documentation at the very least.

**Comment by chaleybgis** [comment]
Just adding my two cents.  To me it is un-intuitive to force menu items not to wrap. Having a menu that overflows fluid width containers by default just doesn't seem right to me.  In the case of a horizontal, scrollable menu, it makes sense. In the previous version, i frequently used the horizontal menu for various interfaces inside of fluid containers.  It made *perfect* sense that they would stack up when the container was getting small.  This change just feels broken.  At any rate, a note in the documentation about restoring (adding) menu wrapping would be tops.

**Comment by jharaphula** [comment]
This menu is designed using pure #CSS, so according to your requirement you can Configure this #menu easily. You can change width, height, font style, font color or font size as you want. To update colors & theme you can update background for li & anchor elements. To present mouse over effect here I used CSS #hover. To update hover related changes you need to update li:hover related classes... [https://goo.gl/Wtlaks](https://goo.gl/Wtlaks)
