### ISSUE TITLE
Buttons in pure-menu

### ISSUE THREAD

**Issue by chaoaretasty** [pure-css/pure#448]
There are times that I would want to include a `button` in a pure-menu instead of an `a` for semantics reasons but the pure-menu-link class isn't enough to remove the default button styling.

Pure allows `a` and `button` to take the pure-button class and look the same so acknowledges a lot of crossover in their usage, I think enabling the same cross use in the menu makes a lot of sense.

**Comment by jamesalley** [comment]
I'll spend some time thinking about this later. The answer may lie in that buttons, obviously, have a lot more default styling than links. Put another way, it's easier to add background and border to a link to make it look like a button, but removing every property of a button so that it looks like plain text might be a trick.

**Comment by chaoaretasty** [comment]
Here's a starter for ten on resetting a button's styles: http://stackoverflow.com/a/12642009

**Comment by redonkulus** [comment]
If this is still wanted, I'm willing to review a PR from the community.
