### ISSUE TITLE
pure-menu-scrollable does not show scrollbar in IE or Chrome

### ISSUE THREAD

**Issue by jeremysimmons** [pure-css/pure#458]
no horizontal scrollbar in the Scrollable Horizontal Menu demo on http://purecss.io/menus/.
Fails in IE11edge, Chrome40.0.2214.115m
Works in FF35.0.1

**Comment by jamesalley** [comment]
This is by design; it's meant to be flicked (by touch) or scrolled with an omnidirectional input such as a trackpad or mouse with omnidirectional scrolling, such as a mouse with a scroll ball, or a Magic Mouse with its trackpad-like flickable surface. A known weakness or design flaw with this construct is that it's not scrollable with a traditional, one- or two-button, point-and-click mouse. Those input devices are typically associated with desktop computers (or laptop users who prefer to use a mouse). Those computers have relatively large displays. So I recommend that you design your UI such that the menu is clipped (and in need of scrolling) only on smaller devices (read: mobile). Alternatively, you could selectively apply the `.pure-menu-scrollable` class only if certain conditions were met.

I admit, I didn't even realize this was a problem for awhile, because all my input devices, whether touchscreen, trackpad, or mouse, let me flick horizontally.

**Comment by 7ammer** [comment]
This IS and issue for those with a standard mouse and single axis scroll wheel

**Comment by LiaungYip** [comment]
There's also no indication that vertical scrolling is even possible.

Below, in Chrome Version 55.0.2883.87 m (64-bit)

![image](https://cloud.githubusercontent.com/assets/2173684/21559398/99063d22-ce86-11e6-944e-eeca8df6f383.png)

There are another seven items to the right, which aren't displayed.

**Comment by magikstm** [comment]
Tested today on Windows 7 x64:
- Firefox 63.0 - Works
- Chrome 70.0 - No visible vertical scrollbar
- IE11 11.0.90 - No visible vertical scrollbar

I suggest labelling this as a "bug".

**Comment by lkraav** [comment]
Yep, confirmed, this component does have x-browser and ux issues described above.

All could use some PR love, if anyone has enough interest.

**Comment by magikstm** [comment]
I tested and issue is still present. This should be labeled as a "bug" and be considered.
