### ISSUE TITLE
Button alignment in aligned form (on small screen sizes)

### ISSUE THREAD

**Issue by prjm** [pure-css/pure#469]
On small screen sizes, the vertical alignment of different button kinds differs
(using an aligned form and the 'pure-controls' button container)

On larger screens:

![image](https://cloud.githubusercontent.com/assets/11259216/6791831/7fe1a084-d1b2-11e4-9321-d982bdcf7b35.png)

On smaller screens:

![image](https://cloud.githubusercontent.com/assets/11259216/6791865/b3b8e11a-d1b2-11e4-830f-c2a081625525.png)

Demo here: http://jsfiddle.net/prjm/vuz8m663/

Am I missing something?

**Comment by jamesalley** [comment]
The problem is with the margin on the submit button. To fix this problem immediately, adjust the margin for `.pure-form button[type=submit]`. I will leave this issue open, I might need to fix that margin in Pure.

**Comment by jamesalley** [comment]
In other words, this has nothing to do with the form being `pure-form-aligned` or with using the `pure-controls` construct, or the screen size per se.

**Comment by jamesalley** [comment]
So, this rule was written to give submit buttons a little extra margin when the screen size is small and the buttons tend to stack vertically. I think this decision should be revisited and possibly this declaration should be removed. This will take some time to consider and test, so I'll create a task for myself.

For now, you can either change the margin as I mentioned above, or just use an input instead of a button. That is, change `<button type="submit" ...>` to `<input type="submit" ...>`

**Comment by arnoldsandoval** [comment]
@jamesalley thought that might be the case - I was looking around the docs for full-width buttons (trying to familiarize myself with the codebase) can you point me to where that is? I didn't see it in the buttons section.

**Comment by jamesalley** [comment]
I don't think there are any full-width button constructs, you'll have to add a class for that yourself.

**Comment by jamesalley** [comment]
e.g., 

```
.full-width {
    width: 100%;
}
```

**Comment by prjm** [comment]
Thank you for the quick support.
I was just wondering why the margin was applied only to submit buttons.
Of course, its a good idea to maximize buttons on small screens.
