### ISSUE TITLE
Improve: Responsive Horizontal-to-Vertical Menu

### ISSUE THREAD

**Issue by inexist3nce** [pure-css/pure#495]
The responsive menu at http://purecss.io/layouts/tucked-menu-vertical/ does not adjust height as one would expect.

When viewing in a screen smaller than 768px, the _"responsive"_ menu has a fixed height that could potentially cause issues with long menus (or in really small screens with wrapping text).

This can be fixed by replacing the hardcoded `height: 14em;` at line 69 with `height: auto;`.

![image](https://cloud.githubusercontent.com/assets/10874672/7786860/a8c00e14-01be-11e5-8e99-3e88a67c09b7.png)

**Comment by jamesalley** [comment]
Thanks for the report and suggestion. I'll re-examine this when I next release the [pure-site](https://github.com/yahoo/pure-site/).

It's possible that I started with auto but discovered a certain browser was having trouble unless I explicitly set the height, so keep browser vagaries in mind.

**Comment by qskousen** [comment]
I recently found out this gets worse when you have more menu items - they get cut off after the 14em.

**Comment by redonkulus** [comment]
@inexist3nce @qskousen only problem with adding `height:auto` is that the transition animation does not work anymore, since you cannot transition to `auto`. This might be a case where the application either removes the animation and thus can have a flexible height. Or just manually calculates the height based on how many items are in it.

**Comment by MikeiLL** [comment]
Wondering if this ties into my issue where child-items in the vertical version of the nav [don't open on hover](https://stackoverflow.com/questions/45967999/responsive-menu-with-dropdown-elements). Can be seen here in this [CodePen](https://codepen.io/MikeiLL/pen/MvZyVO). 

Or is this expected behavior and I need to handle showing child items on my own in the vertical version of the menu?

**Comment by Diegodevops26** [comment]
Invés de melhorar vai acabar piorando, esta fora do padrão deveria ser assim                                                                                                                    
/* Antes da modificação */
.menu {
    height: 14em; /* Linha 69 */
}

/* Após a modificação */
.menu {
    height: auto; /* Ajusta a altura automaticamente */
}
