### ISSUE TITLE
Horizontal scrollbars in Firefox OSX w/Retina display

### ISSUE THREAD

**Issue by klimkjar** [pure-css/pure#497]
In the case of a grid with stacked columns, horizontal scrollbars show up in OSX Firefox on high-dpi displays. The scrollbars are not necessary, and disappear if the window is moved to an external non-Retina monitor. On Chrome the correct behaviour is seen, no scrollbars on either display.

Small test case to reproduce:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Scrollbars</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive.css">
</head>
<body>
  <div class="pure-g">
    <div class="pure-u-1"></div>
    <div class="pure-u-1"></div>
  </div>
</body>
</html>
```

Tested under Firefox 38.0.1 on OSX Yosemite 10.10.3 on a MacBook Pro Retina 15".

**Comment by jamesalley** [comment]
There are several issues which have been filed related to Firefox being just one pixel too wide, resulting in horizontal scrollbars as seen here. Setting .pure-u-1-1 to width 99.99% (instead of 100%) solves the problem and would probably work fine in other browsers as well, but it's a hacky solution to a problem that is clearly a browser bug.

I'm going to leave this open and mark it as a bug but I'm not sure what I can do to fix it in Pure apart from applying the hacky solution, but I don't want to do that as it could result in the grid being 1px too _small_ at a later date (when they fix this) or in another browser.

**Comment by klimkjar** [comment]
Thanks for the response and info. I suppose it could be the same issue as [bug 919281@Bugzilla] (https://bugzilla.mozilla.org/show_bug.cgi?id=919281). I'll link to this issue from there and see if I can hack around it like you suggest after I finalize my layout.

**Comment by jamesalley** [comment]
Yes! There it is. Thanks for digging up the FF bug link.

**Comment by jamesalley** [comment]
Another way to fix this is to remove the letter-spacing on .pure-g and set it to normal. The letter spacing is supposed to collapse whitespace between grid units. I'd have to do a bunch of cross-browser testing before I change or remove that value from Pure, but it may be a way to fix this without involving Mozilla.

**Comment by klimkjar** [comment]
Setting
````css
.pure-g { letter-spacing: normal; }
````
looks like a good workaround for now. Thanks!
