### ISSUE TITLE
There should be a block wide button

### ISSUE THREAD

**Issue by mariosant** [pure-css/pure#585]
There is a very handy tool that I am missing in Pure. This would be the ability to create block wide buttons with a simple class. I know, this can be done very easily with a `width: 100%;`, it would still make a very useful addition.

A quick list of how other frameworks deal with it:
- Foundation: http://foundation.zurb.com/sites/docs/button.html#sizing
- Bootstrap: http://getbootstrap.com/css/#buttons-sizes
- Buttons: http://unicorn-ui.com/buttons/builder/#block

**Comment by lkraav** [comment]
Button width must often be different across media queries. How do you propose solving that with Pure semantics?

**Comment by mariosant** [comment]
I suggest using the pattern that is being used in grids too. Something like `.md-expand` or so, should do the trick.

**Comment by lkraav** [comment]
FWIW I think this idea was on the right track. Instead of introducing new class names, button sizing could follow input sizing semantics at https://purecss.io/forms/#input-sizing

But as I'm moving away from Pure towards web components and utility systems (Vaadin Lumo Styles, Tailwind CSS), I probably won't explore button sizing further here.
