### ISSUE TITLE
Grids not working in mobile (e.g. android 4) even using latest versions of Opera Mini, Dolphin Zero, etc.

### ISSUE THREAD

**Issue by horacioj** [pure-css/pure#686]
### Description

Grids not working in mobile (e.g. android 4) even using latest versions of Opera Mini, Dolphin Zero, etc.

### Expected behavior
The grid doesn't cover the screen size. It doesn't matter if the grid is responsive or not.

This is the right / expected behavior. Example screenshots taken in a device running Android 7, using the same browser versions.

![android_v7_screenshot_20171225-222129](https://user-images.githubusercontent.com/984821/34344299-445dc0b6-e9c3-11e7-92cd-f88983a5d708.jpg)

![android_v7_screenshot_20171225-230401](https://user-images.githubusercontent.com/984821/34344788-27c99fba-e9c8-11e7-86b5-7b5abe2334e3.jpg)

Could it be, the the problem is the outdated WebView, which cannot be upgraded in Android < version 5?

Is this a known issue? Is there a workaround or solution for this? We aren't taking about IE 6 here... there are lots of Android 4 devices out there, and these browsers have lots of users. E.g. Opera Mini has more than 100  million downloads.

### Actual behavior

This is how the grid behaves in Android < version 5. 

Notice the problem can be seen even at [https://purecss.io/start/](https://purecss.io/start/). 
See the **Thirds**
![android_v422_screenshot_2017-12-25-22-15-25](https://user-images.githubusercontent.com/984821/34344300-44829030-e9c3-11e7-85a0-3355bb6dcd1d.jpg)

![android_v422_screenshot_2017-12-25-22-15-33](https://user-images.githubusercontent.com/984821/34344301-44a57a64-e9c3-11e7-813f-48f32c21d7a3.jpg)

### Steps to Reproduce
The problem can be reproduced with this minimal basic code:
```html
<div class="pure-g">
    <div class="pure-u-1-3"> loren </div>
    <div class="pure-u-1-3"> imsum dolor </div>
    <div class="pure-u-1-3"> whatever the thing </div>
</div>
```

### Environment

* Pure version: 1.0.0
* Browser name and version: Android Opera Mini 32.0 (Dec 4, 2017),  Android Dolphin Zero 1.3 
* Link to your project or example: 
Live examples: [http://jsbin.com/regerewelo](http://jsbin.com/regerewelo)
Editable example: [http://jsbin.com/regerewelo/edit?html,output](http://jsbin.com/regerewelo/edit?html,output)

**Comment by gresakg** [comment]
This is not the right way of using mobile grid. This is the right way
```
<div class="pure-g">
    <div class="pure-u-1 pure-u-md-1-3"> ... </div>
    <div class="pure-u-1 pure-u-md-1-3"> ... </div>
    <div class="pure-u-1 pure-u-md-1-3"> ... </div>
</div>
```

**Comment by horacioj** [comment]
No. It's exactly the same. I simply wrote the more simple version of it (excluding any media rule.). As said, you can see the error even browsing   https://purecss.io/start/.

**Comment by 88kbbq** [comment]
In response to this issue, I'll add here that implementing pure.css has been more difficult than anticipated. We chose it because it was an easy library to make AMP compliant and most of our customer base is stuck using old browsers, although we've added the following classes to help with this and similar problems. Be aware that the demo layouts are not compatible with each other and will need changes if adopting these additions.

`@media screen and (max-width:35.499em){.pure-u-xs-1,.pure-u-xs-1-1,.pure-u-xs-1-12,.pure-u-xs-1-2,.pure-u-xs-1-24,.pure-u-xs-1-3,.pure-u-xs-1-4,.pure-u-xs-1-5,.pure-u-xs-1-6,.pure-u-xs-1-8,.pure-u-xs-10-24,.pure-u-xs-11-12,.pure-u-xs-11-24,.pure-u-xs-12-24,.pure-u-xs-13-24,.pure-u-xs-14-24,.pure-u-xs-15-24,.pure-u-xs-16-24,.pure-u-xs-17-24,.pure-u-xs-18-24,.pure-u-xs-19-24,.pure-u-xs-2-24,.pure-u-xs-2-3,.pure-u-xs-2-5,.pure-u-xs-20-24,.pure-u-xs-21-24,.pure-u-xs-22-24,.pure-u-xs-23-24,.pure-u-xs-24-24,.pure-u-xs-3-24,.pure-u-xs-3-4,.pure-u-xs-3-5,.pure-u-xs-3-8,.pure-u-xs-4-24,.pure-u-xs-4-5,.pure-u-xs-5-12,.pure-u-xs-5-24,.pure-u-xs-5-5,.pure-u-xs-5-6,.pure-u-xs-5-8,.pure-u-xs-6-24,.pure-u-xs-7-12,.pure-u-xs-7-24,.pure-u-xs-7-8,.pure-u-xs-8-24,.pure-u-xs-9-24{display:inline-block;zoom:1;letter-spacing:normal;word-spacing:normal;vertical-align:top;text-rendering:auto}.pure-u-xs-1-24{width:4.1667%}.pure-u-xs-1-12,.pure-u-xs-2-24{width:8.3333%}.pure-u-xs-1-8,.pure-u-xs-3-24{width:12.5%}.pure-u-xs-1-6,.pure-u-xs-4-24{width:16.6667%}.pure-u-xs-1-5{width:20%}.pure-u-xs-5-24{width:20.8333%}.pure-u-xs-1-4,.pure-u-xs-6-24{width:25%}.pure-u-xs-7-24{width:29.1667%}.pure-u-xs-1-3,.pure-u-xs-8-24{width:33.3333%}.pure-u-xs-3-8,.pure-u-xs-9-24{width:37.5%}.pure-u-xs-2-5{width:40%}.pure-u-xs-10-24,.pure-u-xs-5-12{width:41.6667%}.pure-u-xs-11-24{width:45.8333%}.pure-u-xs-1-2,.pure-u-xs-12-24{width:50%}.pure-u-xs-13-24{width:54.1667%}.pure-u-xs-14-24,.pure-u-xs-7-12{width:58.3333%}.pure-u-xs-3-5{width:60%}.pure-u-xs-15-24,.pure-u-xs-5-8{width:62.5%}.pure-u-xs-16-24,.pure-u-xs-2-3{width:66.6667%}.pure-u-xs-17-24{width:70.8333%}.pure-u-xs-18-24,.pure-u-xs-3-4{width:75%}.pure-u-xs-19-24{width:79.1667%}.pure-u-xs-4-5{width:80%}.pure-u-xs-20-24,.pure-u-xs-5-6{width:83.3333%}.pure-u-xs-21-24,.pure-u-xs-7-8{width:87.5%}.pure-u-xs-11-12,.pure-u-xs-22-24{width:91.6667%}.pure-u-xs-23-24{width:95.8333%}.pure-u-xs-1,.pure-u-xs-1-1,.pure-u-xs-24-24,.pure-u-xs-5-5{width:100%}}@media screen and (max-width:35.438em){.pure-hidden-xs,.pure-visible-lg,.pure-visible-md,.pure-visible-sm,.pure-visible-xl{display:none}}@media screen and (min-width:35.5em) and (max-width:47.938em){.pure-hidden-sm,.pure-visible-lg,.pure-visible-md,.pure-visible-xl,.pure-visible-xs{display:none}}@media screen and (min-width:48em) and (max-width:63.938em){.pure-hidden-md,.pure-visible-lg,.pure-visible-sm,.pure-visible-xl,.pure-visible-xs{display:none}}@media screen and (min-width:64em) and (max-width:79.938em){.pure-hidden-lg,.pure-visible-md,.pure-visible-sm,.pure-visible-xl,.pure-visible-xs{display:none}}@media screen and (min-width:80em){.pure-hidden-xl,.pure-visible-lg,.pure-visible-md,.pure-visible-sm,.pure-visible-xs{display:none}}@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {.is-center,.splash{text-align:center}.content-head,.splash{text-transform:uppercase}*{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}body{line-height:1.7em;color:#7f8c8d}h1,h2,h3,h4,h5,h6,label{color:#34495e}.pure-img-responsive{max-width:100%;height:auto}.l-box{padding:1em}.l-box-lrg{padding:2em}.pure-form label{margin:1em 0 0;font-weight:700;font-size:100%}.pure-form input[type]{border:2px solid #ddd;box-shadow:none;font-size:100%;width:100%;margin-bottom:1em}.pure-button{background-color:#1f8dd6;color:#fff;padding:.5em 2em;border-radius:5px}a.pure-button-primary{background:#fff;color:#1f8dd6;border-radius:5px;font-size:120%}.home-menu{padding:.5em;box-shadow:0 1px 1px rgba(0,0,0,.1);background:#2d3e50}.pure-menu.pure-menu-fixed{border-bottom:none;z-index:4}.home-menu .pure-menu-heading{color:#fff;font-weight:400;font-size:120%}.home-menu .pure-menu-selected a{color:#fff}.home-menu a{color:#6FBEF3}.home-menu li a:focus,.home-menu li a:hover{background:0 0;border:none;color:#AECFE5}.splash-container{background:#1f8dd6;z-index:1;overflow:hidden;width:100%;height:88%;top:0;left:0;position:fixed}.splash{margin:auto;position:absolute;top:100px;left:0;bottom:0;right:0}.splash-head{color:#fff;border:3px solid #fff;padding:1em 1.6em;font-weight:100;border-radius:5px;line-height:1em}.splash-subhead{color:#fff;letter-spacing:.05em;opacity:.8}.content-wrapper{position:absolute;top:87%;width:100%;min-height:12%;z-index:2;background:#fff}.content{padding:1em 1em 3em}.content-head{font-weight:400;letter-spacing:.1em;margin:2em 0 1em}.content-head-ribbon{color:#fff}.content-subhead{color:#1f8dd6}.content-subhead i{margin-right:7px}.ribbon{background:#2d3e50;color:#aaa}.footer{background:#111;position:fixed;bottom:0;width:100%}body{font-size:16px}.l-box-lrg{border:none}
}`

**Comment by magikstm** [comment]
Did anyone confirm exact Android versions having this issue?

Has this been fixed?

**Comment by horacioj** [comment]
> exact Android versions 

all android 4 flavors and earlier 

> Has this been fixed?

I don't think so
