### ISSUE TITLE
Blog not updated

### ISSUE THREAD

**Issue by fetmar** [pure-css/pure#701]
### Description

Sorry if this is the wrong place to put this. It looks like the address http://blog.purecss.io/ contains a tumblr blog chronicling development, but hasn't been updated to include anything after v0.6.0.

**Comment by redonkulus** [comment]
You are correct, that is where the blog was historically published. I don't actually have access to that blog right now since I've been maintaining Pure. I need to reach out to the former maintainers to get access. But generally, the only new post would be about the v1.0.0 release that is in the [release notes](https://github.com/pure-css/pure/releases/tag/v1.0.0).

**Comment by DrakeXiang** [comment]
Is this project dead or something? Last release was a year ago...

**Comment by redonkulus** [comment]
My post from a few months ago still applies. This project is basically stable. No new development is happening. If a new maintainer wants to come in and revitalize it, then I’m happy to help facilitate.
