### ISSUE TITLE
secondary-button pure-button does not work for input type="button"

### ISSUE THREAD

**Issue by rzorzorzo** [pure-css/pure#721]
### Description

[Description of the bug or feature]
I had issues with button for IE and Edge and had to switch to input type="button".

However purecss does not support this.

### Expected behavior

pure-button and other button styles should also work for input tag

### Environment
* Pure version: latest

**Comment by abnersajr** [comment]
@rzorzorzo I've tried to find your issue but I can't replicate that.
Could you provide a sandbox link to this?

The `secondary-button` class is a custom class used to doc purpose only.
You won't find this class in PureCSS bundle.
By the way, the class `pure-button` is working well.

It's a long time since you had opened this issue, are you still with this problem yet or can we close the issue?
