### ISSUE TITLE
Dropdown menu not working in Mobile Version

### ISSUE THREAD

**Issue by omarcaccia** [pure-css/pure#756]
### Description

Hi everyone, I'm using PureCSS last version and I created an horizontal menu with dropdown, following the instructions on the main page.

### Expected behavior
The dropdown menu is supposed to appear under the "has-children" menu voice in mobile.

### Actual behavior
The dropdown menu shows up on desktop, but not on mobile.

### My mods

I had a first issue: the dropdown didn't show on desktop and I had to change .custom-wrapper to overflow:visible; while in responsive mode (below 768px) is set to hidden. In this way, the dropdown menu is visible on desktop version, but nothing happens when I change to mobile version. I see the "has-children" menu voice but dropdown menu doesn't appear on mobile.

### Environment

* Pure version: last version available
* Browser name and version: Vivaldi, Chrome, Firefox, Android, Safari
* Link to your project or example: http://mirkosatto.it

**Comment by aaronpinero** [comment]
There are a few issues involved.

First, there is the example on which the menu was based (which I believe is https://purecss.io/layouts/tucked-menu-vertical/). This example menu doesn't afford for a dropdown within the menu.

The example for a vertical menu with a dropdown that is provided in the Pure documentation (https://purecss.io/menus/#vertical-menu-with-submenus) has some JavaScript associated with it. Basically, the dropdown in a vertical menu (which is what the mobile menu uses) is activated by toggling the `pure-menu-active` class on the <li> that contains the dropdown. If you manually alter the code in your site's menu to add this class, the dropdown style will change from display:none to display:block.

Then there is an additional problem. The styles for a dropdown in a vertical menu have the dropdown positioned on the left of the parent link. Since your mobile menu is the full width of the viewport, your dropdown menu isn't actually visible. To make this work, it would be necessary to change the styles for the dropdown menu so they appear in the viewport. If you inspect your page and manually change the left position of the dropdown menu, you can make it appear in the viewport.

Putting this all together, it would probably be necessary to selectively merge the JavaScript from the two examples so that the mobile menu has the correct function. Then, the styles of the vertical menu dropdown (for mobile) would need to be customized for this use case. It would be  helpful to add a responsive menu recipe to address this (probably very common) use case.
