### ISSUE TITLE
Example provided for Responsive Vertical Menu might not actually work

### ISSUE THREAD

**Issue by ginger51011** [pure-css/pure#809]
### Description

I was unsure if I should post this here, but I regard it as a problem in the docs.

On the purecss.io website, an [example](https://purecss.io/layouts/side-menu/) for a responsive vertical menu, similar to the one on the purecss website, is provided. I copy-pasted it on my own project and I do quite like it but it seems like when you actually open the hamburger-menu and follow a link the menu simply closes, without following the link. I tried inspecting the source on the example page and changed one of the hrefs in that menu to actually redirect somewhere, but I got the same result.

I might very well be in the wrong here, so please point me in the right direction in that case.

### Expected behavior

When opening the hamburger menu and then clicking a link, the user should be redirected.

### Actual behavior

The hamburger menu closes.

### Steps to Reproduce

1. Follow installation instructions on this [page](https://purecss.io/layouts/side-menu/)
2. Deploy a test site with links in the menu
3. Visit the site in a window small enough to make the hamburger menu appear
4. Click any link

### Environment

* Pure version: 2.0.3
* Browser name and version: Chrome, Firefox

**Comment by redonkulus** [comment]
The [JS](https://purecss.io/js/ui.js) on the page is very basic and meant to demo very simple menu toggle. You will need to create your own script or modify the existing one to open links properly.

**Comment by johncalab** [comment]
I'm actually facing the same issue, but unfortunately I don't have enough js experience to understand how to change the ui.js file in order to make the links match with those already present in the html. Any help would be greatly appreciated!

**Comment by johncalab** [comment]
Maybe I can clarify where my difficulty is.
For the sidebar entries, I have hyperlinks in the html code. I don't understand where in the JS file I should specify that the sidebar entries should still point to the same urls.

**Comment by tbydza** [comment]
You don't need to change JS file.  Look at these examples.

Clicking on this:
```<li class="pure-menu-item"><a href="#contacts-id" class="pure-menu-link">Contacts</a></li>```
will focus and scroll to this element on the same page:
```<element id="contacts-id"></element>```

Clicking on this:
```<li class="pure-menu-item"><a href="http://purecss.io/" class="pure-menu-link">Pure.css</a</li>```
will redirect you to another page.

**Comment by alexishuxley** [comment]
Perhaps this is related to the integrity key that the [Getting Started page](https://purecss.io/start/) specifies being wrong?

That page currently (28 October 2020) says to add this:

`<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/pure-min.css" integrity="sha384-4ZPLezkTZTsojWFhpdFembdzFudphhoOzIunR1wH6g1WQDzCAiPvDyitaK67mp0+" crossorigin="anonymous">`

But this key is wrong and results in pages not being formatted according to the examples (e.g. the [default table](https://purecss.io/tables/#default-table) misses borders, bold and background colours).

Change the key to the one currently documented on [github](https://github.com/pure-css/pure/), i.e.

`<link rel="stylesheet" href="https://unpkg.com/purecss@2.0.3/build/pure-min.css" integrity="sha384-cg6SkqEOCV1NbJoCu11+bm0NvBRc8IYLRGXkmNrqUBfTjmMYwNKPWBTIKyw9mHNJ" crossorigin="anonymous">`

and suddenly it works.

**Comment by rouyng** [comment]
@johncalab Were you able to resolve this? I'm having the same issue. My ui.js is unmodified and all my menu items are per @tbydza 's examples. I can also see that the purecss.io site has a working menu using the same exact ui.js file, so that doesn't seem to be the issue. Thanks from one JS neophyte to another.

**Comment by redonkulus** [comment]
I've figured out the issue here. So this `ui.js` is used on the static layout pages and the main Pure website. `e.preventDefault()` was used inside the `toggleAll` function to prevent the links from being followed, but as mentioned in this issue, it prevented navigation links from working. This wasn't seen on the Pure website because Docusaurus handles the link following automatically. 

For the [fix](https://github.com/pure-css/pure/commit/4c01e2c5edcd2b40ef218ddfe1f145661fad9615), I removed the `preventDefault`, this ensures the links are now followed. However, this did create a bug on the Pure site where the menu would no longer work after clicking a link. It turns out that Docusaurus was refreshing the  elements that were referenced in the `ui.js`, which prevented the menu from working. My simple fix was just to [get the elements on the fly](https://github.com/pure-css/pure/commit/4c01e2c5edcd2b40ef218ddfe1f145661fad9615#diff-c45faa9a43bc12621970cc4a00c00e311423027f458ae4a3642a570061a06c0eR3) each event to avoid referencing stale elements.

You shouldn't need the same fix that I did as this was only for the Pure website. In your own `ui.js` just remove the `e.preventDefault()` and your links should work as usual.
