### ISSUE TITLE
Just A Quick Question...

### ISSUE THREAD

**Issue by Aspiring-Writer** [pure-css/pure#830]
I am learning web development and I just read about some new tags in HTML5, ie. main, content, nav, etc, and I was wondering why doesn't PureCSS use those tags instead of classes in div tags?

I'm sorry if this question is a nuisance, I was just curious because I want to use Pure in my own project and I wasn't sure if there was a specific reason for the classes.

**Comment by redonkulus** [comment]
Best thing to look up is semantic HTML. This will explain why using the correct tags to decorate your markup is important for accessibility, search engine optimization and other important things. 

Note, that you have to use backticks (`<h1>hi</h1>`) around the html tags on GitHub, otherwise they do not display properly.

**Comment by Aspiring-Writer** [comment]
Oh, okay. Thanks so much!
